# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-16 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170916_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subscribes',
            field=models.ManyToManyField(blank=True, to='blog.Profile'),
        ),
    ]
