# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-17 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170917_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='blog.Profile', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='readedpost',
            name='readed',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Прочитано'),
        ),
    ]
