# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-17 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170917_1901'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='readedpost',
            unique_together=set([('post', 'user')]),
        ),
    ]
